esphome:
  name: dsmr-reader

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:
  password: "bdb3d1b566u5cfa9d5910a4bea39a4aa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dsmr-Reader Fallback Hotspot"
    password: "DiBspO7WECmE"

captive_portal:

uart:
  id: uart_p1
  rx_pin: GPIO13
  baud_rate: 115200
  rx_buffer_size: 1700

dsmr:
  uart_id: uart_p1
  request_pin: GPIO12
  request_interval: 5000ms

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: Energy Consumed Tariff 1
    energy_delivered_tariff2:
      name: Energy Consumed Tariff 2
    energy_returned_tariff1:
      name: Energy Returned Tariff 1
    energy_returned_tariff2:
      name: Energy Returned Tariff 2
    power_delivered:
      name: Power Consumed
    power_returned:
      name: Power Produced
    electricity_failures:
      name: Electricity Failures
    electricity_long_failures:
      name: Long Electricity Failures
    voltage_l1:
      name: Voltage Phase 1
    voltage_l2:
      name: Voltage Phase 2
    voltage_l3:
      name: Voltage Phase 3
    current_l1:
      name: Current Phase 1
    current_l2:
      name: Current Phase 2
    current_l3:
      name: Current Phase 3
    power_delivered_l1:
      name: Power Consumed Phase 1
    power_delivered_l2:
      name: Power Consumed Phase 2
    power_delivered_l3:
      name: Power Consumed Phase 3
    power_returned_l1:
      name: Power produced Phase 1
    power_returned_l2:
      name: Power produced Phase 2
    power_returned_l3:
      name: Power produced Phase 3
    gas_delivered:
      name: Gas Consumed

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
    # timestamp:
    #   name: "Timestamp"
    electricity_tariff:
      name: "Current Tariff"
    # electricity_failure_log:
    #   name: "Electricity Failure Log"
    # message_short:
    #   name: "Message short"
    # message_long:
    #   name: "Message long"
    # gas_equipment_id:
    #   name: "Gas Equipment Id"
    # water_equipment_id:
    #   name: "Water Equipment Id"
    # sub_equipment_id:
    #   name: "Sub Equipment Id"
    # gas_delivered_text:
    #   name: "Gas Delivered Text"